### ISSUE TITLE
ImportError: cannot import name 'Gt' from 'annotated_types'

### ISSUE THREAD

**Issue by ychen878** [annotated-types/annotated-types#11]
Hi,

I got an `ImportError` when I was trying to import `Gt`:
```
ImportError: cannot import name 'Gt' from 'annotated_types'
    (/root/venv/lib/python3.9/site-packages/annotated_types/__init__.py)
```
I tried installing and using the package on my personal computer (Python 3.9.12) and an EC2 instance (Python 3.9.13). The same error showed. I am wondering how to solve the problem.

Thanks!

**Comment by adriangb** [comment]
@samuelcolvin I think we need to cut the release

**Comment by samuelcolvin** [comment]
Sounds good to me. What do I need to do?

How is this related?

**Comment by adriangb** [comment]
The release on PyPi is the placeholder with no code, hence the import error. We should yank that one. I invoked you because you set up the template to cut releases, I don't want to mess it up.

**Comment by samuelcolvin** [comment]
Makes sense. I think no need to yank, just publish a new release.

I think just go ahead and publish, and we can fix from there. Let me know if you need my help.

**Comment by adriangb** [comment]
Resolved @ychen878 , thank you for reporting!

**Comment by samuelcolvin** [comment]
Thanks so much @adriangb much appreciated.
