### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by samuelcolvin** [annotated-types/annotated-types#17]
I've started using this in pydantic :tada:, can we get a new release please so I haven't done too much with v0.2 before the next release.

**Comment by adriangb** [comment]
https://github.com/annotated-types/annotated-types/releases/tag/untagged-ad3c56e367b52ea46aa4

Remind me: we just publish the tag on GitHub and CI will release on PyPi right?

**Comment by samuelcolvin** [comment]
I think we need to change

https://github.com/annotated-types/annotated-types/blob/7351d1bf7c1ea1a9828f92356aea7b0096c50601/annotated_types/__init__.py#L44

Then just create a release.

**Comment by adriangb** [comment]
Done!

**Comment by samuelcolvin** [comment]
Thanks so much.
