### ISSUE TITLE
Rethink `max_exclusive`, convert to `max_inclusive`?

### ISSUE THREAD

**Issue by samuelcolvin** [annotated-types/annotated-types#23]
If we have `MaxLen`, and (in pydantic at least) that can be set via a `max_length` argument.

I really think this should mean "maximum inclusive", not "maximum exclusive" as currently documented.

This matches (IMHO) much better people's assumption about what `MaxLen(5)` or `max_length=5` or `Len(0, 5)` means:

> "The airbnb allows maximum 5 guests", you would assume 5 guests were allowed, not just 4

If for the sake of correctness, that involves either:
* treating slices differently
* or, removing the recommendation on allowing slices

That's sad, but I think a price worth paying.

At the end of the way `max_length=5` meaning any length up to 4, won't fly in pydantic.

**Comment by samuelcolvin** [comment]
My personal preference would be to treat slices e.g. `2:10` as `Len(min_inclusive=2, max_inclusive=10)`.

But I can already hear the rumbling of disagreement as I write that.

**Comment by Zac-HD** [comment]
Yeah, this is a compelling argument. Let's remove slices and make both inclusive, and consider changing the name - min/max_len would match the other names, or min/max_size would match Hypothesis.

**Comment by samuelcolvin** [comment]
Agreed, I'd prefer `min_length` / `max_length` to match `MinLen` / `MaxLen` / `Len`, but easy on that.

**Comment by samuelcolvin** [comment]
I'll submit a PR once #21 is merged.
