### ISSUE TITLE
Operator based `BaseMetadata` creation

### ISSUE THREAD

**Issue by hanjinliu** [annotated-types/annotated-types#28]
Hi all,
I really like the idea of `BaseMetadata` to formulate `Annotated` types.

However, configuration using functions such as `Gt(10)` is not as easy as `x > 10` to read. It would be nice to provide a non-constraint class `All` and support methods such as `__gt__` like below.

```python
class All(BaseMetadata):
    def __gt__(self, other):
        return Gt(other)

X = All()  # could be better to keep `All` private and provide `X` publically.
Annotated[int, X > 5]  # equivalent to Annotated[int, Gt(5)]
```

Similar logic can by applied to construct several objects.

- `Interval` from `2 < X < 5`
- `MultipleOf` from `X % 3 == 0`
- `MaxLen` from `X.len() <= 10`

**Comment by Zac-HD** [comment]
Ooh, I *really* like this idea!  It's going to be a little tricky to implement support for chained comparisons and `len(X)`, at least if we want to give good error messages when misused, but worth it for how sweet the syntax will be 🤩

**Comment by samuelcolvin** [comment]
Awesome idea, thanks @hanjinliu. I'll review the PR now.

**Comment by hanjinliu** [comment]
Thank you all for the consideration! Looking forward to seeing it.

**Comment by Zac-HD** [comment]
Per #30, this sadly seems too complex and edge-case-prone to support for now.

Nonetheless, we really appreciate your contribution of design feedback 🙏- thanks!
