### ISSUE TITLE
Chained constraints

### ISSUE THREAD

**Issue by adriangb** [annotated-types/annotated-types#31]
Thought from #28: we could also do something like `Exponent = Annotated[int, Gt(0) & MultipleOf(2)]`.

Implementing `&` would be easy: it just creates a `GroupedMetadata`. 

Other operators would be trickier: `Annotated[str, Foo | Bar]` should actually be expressed as `Annotated[str, Bar] | Annotated[str, Foo]`, and I have no idea what XOR would be, I think we’d have to offload that to implementers. So I think this idea has short legs.

**Comment by adriangb** [comment]
Also as “pretty” as `&` seems, it’s not saving any typing.

**Comment by Zac-HD** [comment]
Yeah, `&` can just be spelled `,`; I agree that `|` should be expressed outside the `Annotated[]`, and I don't think that xor is even expressible in Python types at the moment ([without high-grade magic, anyway](https://www.hillelwayne.com/negatypes/)).
