### ISSUE TITLE
Any library levering typing.Annotated for static checks yet ?

### ISSUE THREAD

**Issue by ljak** [annotated-types/annotated-types#33]
Hi, 

I stumbled across `annotated-types` while digging into typing.Annotated and its capabilities. 
The part that catches my attention is the `Predicate` object to be used with Run-times checks.

Then I check if any tools is levering the library, and it seems that even typing.Annotated (PEP593) is
not really leveraged by any tool (eg. mypy) for static checks ? Or am I missing something ?

Thanks.

**Comment by samuelcolvin** [comment]
Pydantic v2 will leverage annotated-typea, including `Predicate`.

**Comment by ljak** [comment]
Thanks, will follow more closely the development of Pydantic v2 for that specific aspect. 
My question was broader though: is there any existing tool that leverage typing.Annotated (PEP593) for doing static checks ?

**Comment by adriangb** [comment]
No I don't think any _static_ type checkers use PEP593. They support it insofar as that they _ignore_ it without breaking, but they don't analyze the metadata at all.

**Comment by ljak** [comment]
Thanks for confirming!
