### ISSUE TITLE
TypeError: Interval() takes no arguments

### ISSUE THREAD

**Issue by EMalagolihpa** [annotated-types/annotated-types#42]
Seems to be a python version incompatibility: with a Python 3.9.7 env
```
import annotated_types
annotated_types.Interval(gt=0)
```
gives `TypeError: Interval() takes no arguments`.

If I try with Python 3.9.16 or Python 3.10.11, no errors.

**Comment by adriangb** [comment]
This seems like it's a bug in < `3.9.X`. There's nothing special going on with this class and it works on other Python versions. Sadly I don't think there's anything we can do about this.

**Comment by yagggi** [comment]
I encountered this issue recently, and found out this is a bug only exists in `3.9.7`, [here](https://bugs.python.org/issue45081) is the bug report.
