### ISSUE TITLE
Rename `Len` to `BoundedLen`?

### ISSUE THREAD

**Issue by ajoino** [annotated-types/annotated-types#48]
(Full disclosure: I haven't used this library yet, but will probably soon when we migrate to Pydantic V2 at work!)

I was reading through the code to see how this library works, and I was pleasantly surprise to see how simlpe it is. One thing that stuck out to me was the name of the  `Len` class, so I wanted to suggest renaming it to `BoundedLen` or something similar that describes that the length of the object is bounded. I had to read the docstring to figure out what what the class does, which I didn't really for most other simple types. If you've thought about this before I'd love to hear your reasoning why you chose the name you did.

**Comment by adriangb** [comment]
I do like that name more, but not enough to make a breaking change
