### ISSUE TITLE
Static checking of annotations: Strict vs. lenient?

### ISSUE THREAD

**Issue by JelleZijlstra** [annotated-types/annotated-types#53]
I'm starting to think about adding support for annotated-types in my [pyanalyze](https://github.com/quora/pyanalyze) type checker. Because pyanalyze imports and inspects the code it type checks, unlike a fully static type checker, it should be possible to support all aspects of annotated-types, even `Predicate`.

I have to make a decision, though, about what to do if I don't have enough information. Consider this example:

```python
from annotated_types import Gt
from typing import Annotated, Any, assert_type

def make_it_big(x: Annotated[int, Gt(10)]) -> None: ...

def caller(x: int, very_big_int: Annotated[int, Gt(20)], maybe_big_enough: Annotated[int, Gt(9)], unknown: Any) -> None:
    make_it_big(1) # should fail
    make_it_big(11) # should be accepted
    make_it_big(very_big_int) # should be accepted
    make_it_big(unknown) # should be accepted
    make_it_big(x)  # should be rejected?
    make_it_big(maybe_big_enough)  # should be rejected?
    make_it_big(maybe_big_enough + 1) # ideally should be accepted, but not sure I can feasibly implement it

    if x > 10:
        assert_type(x, Annotated[int, Gt(10)])  # would be nice but maybe not essential
```

I'm curious if you have thoughts about which of these cases it would be useful to accept or reject for users.

**Comment by Zac-HD** [comment]
I think either choice would be reasonable - my personal preference is to minimize false alarms, with (if feasible) an option to enable stricter checks for people who want that.

**Comment by JelleZijlstra** [comment]
I implemented this now in quora/pyanalyze#673. I decided to go with the strict option for now, as I think that's what we'd generally want in the work codebase where we'll apply this. It's feasible to provide an option for lenient checking but I'm leaving it out for simplicity.

**Comment by adriangb** [comment]
That's amazing, I am still in awe that this sort of thing is even possible with a type checker, runtime or not!

**Comment by Zac-HD** [comment]
Closing because I think we resolved the question above, and even saw a really cool implementation ship!
