### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by PelicanQ** [annotated-types/annotated-types#59]
Version: 0.6.0
File: `annotated_types/__init__.py`

Typo: "All it the the constraint"
```
class GroupedMetadata(Protocol):
    """A grouping of multiple BaseMetadata objects.

    `GroupedMetadata` on its own is not metadata and has no meaning.
    All it the the constraint and metadata should be fully expressable
    in terms of the `BaseMetadata`'s returned by `GroupedMetadata.__iter__()`.
```

https://github.com/annotated-types/annotated-types/blob/195e3406a276d3599fb94f6f982f5e91837de4a3/annotated_types/__init__.py#L152C1-L157C79

**Comment by adriangb** [comment]
I belive it should say `All of the constraints`. Would you like to make a PR to fix this typo?
