### ISSUE TITLE
More examples would be helpful

### ISSUE THREAD

**Issue by td-anne** [annotated-types/annotated-types#61]
I am trying to use annotated types to encourage `hypothesis` to automatically generate objects, running into trouble, and realising that I'm really unsure what the intended way to use `annotated-types` is. Concretely, I have written:

```python
FiniteFloat = Annotated[float, IsFinite]
```

Is this correct and idiomatic? How should multiple annotations be handled? Is the following acceptable?

```python
PositiveFloat = Annotated[FiniteFloat, Gt(0)]
```

I don't think annotated types are allowed to be nested like this, or at least `hypothesis` seems to choke on them, so what is the idiomatic way to compose constraints?

There is also some code demonstrating how to create `GroupedMetadata` but no code indicating how it should be used, or what for.

I looked into the test suite, but (perhaps understandably) it doesn't really have any idiomatic simple examples I can draw from.

**Comment by td-anne** [comment]
Upon further reading, the Python typing documentation (https://docs.python.org/3/library/typing.html#typing.Annotated) does not describe the format this package uses for some annotations:

```python
_NumericType = TypeVar('_NumericType', bound=Union[SupportsFloat, SupportsIndex])
IsFinite = Annotated[_NumericType, Predicate(math.isfinite)]
```

Specifically, I can't find any mention of what should happen if you write

```python
FiniteFloat = Annotated[float, IsFinite]
```

which expands to 

```python
FiniteFloat = Annotated[float, Annotated[_NumericType, Predicate(math.isfinite)]]
```

The typing documentation says that nested annotated types should be flattened, but all their examples are about nesting in the *first* argument, that is, multiple annotations applied to the same type.

My guess here is that some tool somewhere is supposed to evaluate whether `float` and `_NumericType` can be reconciled, and if so, flatten this down to a one-layer annotation on `float`. Is this correct? What should happen if the outer type cannot be reconciled with `_NumericType`?

The `test_cases.py` file suggests that one needs to write `Annotated[float, IsFinite[float]]`; is this correct? https://github.com/annotated-types/annotated-types/blob/main/annotated_types/test_cases.py#L129

**Comment by JelleZijlstra** [comment]
`IsFinite` is meant to be a generic type, not a piece of metadata. So you can write `x: IsFinite[float] = 1.0`, or `x: Annotated[IsFinite[float], Gt(0)] = 1.0`, or, equivalently, `x: IsFinite[Annotated[float, Gt(0)]] = 1.0`, but it's not meaningful to write `x: Annotated[float, IsFinite] = 1.0`.

**Comment by td-anne** [comment]
Aha! It would be really useful to have documentation of that.

**Comment by Zac-HD** [comment]
Our README is outright wrong on this!  😱 

We should fix that ASAP...

**Comment by JelleZijlstra** [comment]
Oh indeed, the README says it's defined as `IsFinite = Predicate(math.isfinite)`, but in the code it is `IsFinite = Annotated[_NumericType, Predicate(math.isfinite)]`. Same for the other Is* names.

I actually like what the README is doing better: `x: Annotated[float, IsFinite] = 1.0` looks more natural than `x: IsFinite[float] = 1.0`.

**Comment by Zac-HD** [comment]
Looking through the history, @samuelcolvin originally used that style and then @adriangb switched to generics/typevars.  I also prefer the consistency of having an explicit `Annotated` - IMO that makes it easier for users to transition to writing their own more complex constraints - but I'm not sure it's worth changing now.

**Comment by adriangb** [comment]
I like the generic syntax because it lets you avoid extra boilerplate from `Annotated`. If also lets you type what a constraint can be applied to, e.g. type checkers will be fine with `Annotated[list[float], IsFinite]` but not `IsFinite[list[float]]`.

**Comment by adriangb** [comment]
But in any case it does seem like it's too late to change, we should update the docs.
