### ISSUE TITLE
Fix the type annotation of `GroupedMetadata.__iter__`

### ISSUE THREAD

**Issue by Zac-HD** [annotated-types/annotated-types#66]
[Our README says](https://github.com/annotated-types/annotated-types#integrating-downstream-types-with-groupedmetadata) that `GroupedMetadata`  should be handled by iterating over the object and treating the results as if they had been "unpacked" in the Annotated type.  However, the docstring is specific to `BaseMetadata`, as is the type annotation:

https://github.com/annotated-types/annotated-types/blob/99dbac8103ec938ffc1abd779f2f4316bf5e73e7/annotated_types/__init__.py#L154-L158
https://github.com/annotated-types/annotated-types/blob/99dbac8103ec938ffc1abd779f2f4316bf5e73e7/annotated_types/__init__.py#L188-L189

The README is correct here, since we want to match `typing.Unpack`, so we should update the docstring to describe it as 'a grouping of multiple objects, like typing.Unpack', and annotate the iterable as containing `object`.

(originally identified in this downstream issue: https://github.com/HypothesisWorks/hypothesis/pull/3986#issuecomment-2108238957)

**Comment by cksleigen** [comment]
I'm gonna work with this issue.

**Comment by Vaunty** [comment]
I'm going to be working on this issue.
