### ISSUE TITLE
PEP 746

### ISSUE THREAD

**Issue by jorenham** [annotated-types/annotated-types#76]
I recently notices a new draft PEP, [PEP 746](https://peps.python.org/pep-0746/).
Apart from the (IMO rather awkward) `__supports_type__` API, the idea that's proposed there, is pretty much equivalent to this project. 

But since there's no mention of `annotated-types` in the pep (or any other projects for that matter), and because the "rejected ideas" section doesn't include something like "Why not use a `__call__` instead of `__supports_type__`, so that a `lambda obj: obj > 0` can replace the 12 lines of code in the example?", perhaps the author (`@adriangb` I believe) simply isn't aware of this project. 

Anyway, it might be a good idea to contact the author, or the PEP sponsor; it'd be a nice PEP to have, but it'd be even nicer if this project could make it better :)

**Comment by adriangb** [comment]
I am the author / creator of `annotated-types` and PEP 746, so I am certainly aware of it 😄

> Apart from the (IMO rather awkward) __supports_type__ API, the idea that's proposed there, is pretty much equivalent to this project.

Since `__supports_type__` is only meant to be used by libraries providing metadata (like this one) or advanced user customizations in libraries like Pydantic the awkwardness isn't a big deal really.

I don't see how PEP 746 is _equivalent_ to this project: PEP 746 is meant to make the metadata that libraries like `annotated-types` generate more type-checker friendly. It doesn't replace `annotated-types` in any way.

> Why not use a __call__ instead of __supports_type__, so that a lambda obj: obj > 0 can replace the 12 lines of code in the example?

Can you give a more concrete example? What do you want to "work" here that doesn't? Why is `Predicate(lambda x: x > 0)` not good enough or why not just use `Gt(0)`?

Also see #73

**Comment by jorenham** [comment]
> I am one of the authors / creators of `annotated-types` and PEP 746, so I am certainly aware of both 😄

Ah great, that simplifies thing! But why didn't you mention `annotated-types` in the PEP then?

> Since `__supports_type__` is only meant to be used by libraries providing metadata (like this one) or advanced user customizations in libraries like Pydantic the awkwardness isn't a big deal really.

Well, since I'm the author on one of those libraries (see https://github.com/jorenham/optype/issues/89), it's relevant to me 😉 

> I don't see how PEP 746 is _equivalent_ to this project: PEP 746 is meant to make the metadata that libraries like `annotated-types` generate more type-checker friendly. It doesn't replace `annotated-types` in any way.

Perhaps I misunderstood then, but I was under the impression that both aim to solve the same problem. That's what I meant with "equivalent". 

> > Why not use a **call** instead of **supports_type**, so that a lambda obj: obj > 0 can replace the 12 lines of code in the example?
> 
> Can you give a more concrete example? What do you want to "work" here that doesn't? Why is `Predicate(lambda x: x > 0)` not good enough or why not just use `Gt(0)`?
> 
> Also see #73

It's more DRY, and results in fewer lines of code (i.e. less code to test and maintain), and makes it possible to rely on `operators` / `functools.partial` for many of the common use-cases. And since we're talking about an API for *predicates* here, it "just makes sense" to define them functionally.

But the most important reason is that *there is no state*, and typecheckers cannot deal with one. But using an OOP approach would suggest otherwise. FP (functional programming) on the other hand, doesn't have an concept of "state" (putting functors and monads aside).

It's best to minimize the amount of possible errors that users can make. And in this case, it's easier to make mistakes when writing/using "an instance of a type that implements a `__supports_type__` method", then "a callable".

**Comment by adriangb** [comment]
> It's more DRY, and results in fewer lines of code (i.e. less code to test and maintain)

Are you talking about LOC for users, LOC for libraries implementing PEP 746 or LOC for implementers of PEP 746 support in typecheckers?

> But the most important reason is that there is no state, and typecheckers cannot deal with one.

Are you aware that Pyright already implemented (provisional) support for PEP 746 and that it seemed like a very easy change (few LOC, author said it was one of the easiest typing PEPs they'd implemented)?

Overall it's not clear to me what you are proposing. Do you want `Annotated[int, lambda x: x < 0]` to "just work"?

**Comment by jorenham** [comment]
I'm purely talking about the user-side of the proposed API. 
It's great that it's easy to implement for typeheckers; so it's probably just as easy to modify `__supports_type__` to `__call__`.

**Comment by adriangb** [comment]
Users should never have to type or know about `__supports_type__`. Users will do `Annoatead[int, annotated_types.Gt(0)]` and that will type check but `Annotated[str, annotated_types.Gt(0)]` will not.

**Comment by jorenham** [comment]
I wasn't suggesting that untyped lambda's should "just work"; I don't expect an untyped `def gt0(lhs): lhs > 0` or a `class Gt0: __supports_type__(self, lhs): lhs > 0` to "just work" either.

But don't you agree that 

```python
def gt0(lhs: SupportsGt[Literal[0], bool], /) -> bool:
    return lhs > 0
```

is cleaner in terms of both readability, maintainability, and in purpose, than

```python
class Gt0:
    def __supports__type__(self, lhs: SupportsGt[Literal[0], bool], /) -> bool:
        return lhs > 0
```

---

If you include in the pep that only fully annotated callables are allowed, that behave like *pure functions", then it's perfectly clear what's allowed and what isn't, right?

**Comment by jorenham** [comment]
And it's always still an option to use something like 

```python
class Gt0:
    def __call__(self, lhs: SupportsGt[Literal[0], bool], /) -> bool:
        return lhs > 0
```

**Comment by JelleZijlstra** [comment]
If you feel the PEP should be written differently, the discuss.python.org discussion is probably a better place than here.

I don't agree though that using `__call__` is much cleaner. Lots of things are callable; not all of them make sense to be annotated metadata. Using a separate method name makes it clear what the user meant. There may be a compatibility problem if existing code Annotated metadata elements that are callable but don't follow the PEP 746 protocol.

Your example is just for "greater than 0", but in fact annotated-types exposes a "greater than N" metadata element `Gt(N)`. Implementing that would still require either a class or a nested function.

**Comment by adriangb** [comment]
I'm going to close this since I think discussion should continue in the PEP.
