### ISSUE TITLE
Functionality request: Support conjunction and disjunction

### ISSUE THREAD

**Issue by MattiasDC** [annotated-types/annotated-types#81]
Hi,

I'm finding myself in a situation where I want to combine constraints. I could make it a predicate, but sometimes using conjunctions/disjunctions can be clearer and shorter.

Consider a 'currency' constraint that could be implemented like this:

```python
# Current way 
def currency(cur) -> bool:
    return len(cur) == 3 and cur.is_upper()

class Order:
    currency: Annotated[str, Predicate(currency)]

# Proposed functionality
class Order:
    currency: Annotated[str, Len(3) & IsUpper]

```

Next to `&`, `|` would be for disjunctions. Allowing this would also have as a side-effect that validation packages would be able to improve error messages as to why a certain validation failed.
Does this functionality fit in the vision of this package?

**Comment by MattiasDC** [comment]
Upon further investigation, there seems to be negation support for functors with the `Not` functionality. This is potentially driving my suggestion into an alternative direction using classes:

```python
class Order:
    currency: Annotated[str, And(Len(3), IsUpper, ...)]
```

alternatively the invert operator `~` could be implemented on constraints and could invoke `Not`.
My preference would still be my first suggestion, but throwing this in to fuel discussion.

**Comment by JelleZijlstra** [comment]
I think you can currently do `And` by adding multiple predicates: `Annotated[str, Len(3), IsUpper]`. And you can do `Or` by using a union: `Annotated[str, Len(3)] | Annotated[str, IsUpper]`. I'm not sure anything else is needed.

**Comment by MattiasDC** [comment]
This is already great news, lack of knowledge on my part. I didn't know that multiple metadata arguments could be passed to `Annotated`.
Small downside on the disjunction is on the repeating of `Annotated[str,` but I can live with that.
If someone else asks for this functionality, consider adding an example of it in documentation, otherwise this issue can be closed.

**Comment by MattiasDC** [comment]
Hi @JelleZijlstra ,

I was testing this out and found out that there is a difference between (they both fail):
```python
from annotated_types import Ge, Predicate, Len
from pydantic import BaseModel
from typing import Annotated

class PriceBroken(BaseModel):
    value: Annotated[float, Ge(0)]
    currency: Annotated[str, Len(3, 3), Predicate(str.isupper)]

class PriceAlsoBroken(BaseModel):
    value: Annotated[float, Ge(0)]
    currency: Annotated[str, Predicate(str.isupper), Len(3, 3)]

pb = PriceBroken(value=1.0, currency='USD')
print(pb.currency == 'USD')
pab = PriceAlsoBroken(value=1.0, currency='USD')
```

`pb.currency` ends up being `None`.
`pab` creation fails with `TypeError: object of type 'NoneType' has no len()`.
Care to give some more help, or reopen the issue?

**Comment by JelleZijlstra** [comment]
I don't have permissions to reopen issues here, but what you report feels more like a bug in Pydantic. What annotated-types could do is documenting that `Annotated[str, pred1, pred2]` means both pred1 and pred2 should apply.
